### ISSUE TITLE
ID is not highlighted

### ISSUE THREAD

**Issue by SubstanceDesign** [danielbayley/atom-language-postcss-sugarss#1]
if I write: 

section#call-interest.centered-column-with-image

then ID not highlighted.

I use plugin for atom: language-postcss-sugarss, v0.1.0

**Comment by danielbayley** [comment]
@SubstanceDesign From the README:
> NOTICE: THIS PACKAGE IS DEPRECATED

Please use [language-postcss](https://atom.io/packages/language-postcss) instead.
